name: Build rustwii

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-x86_64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # Not sure if this is the best choice, but I'm building in release mode to produce more effective nightly binaries.
    - name: Update Toolchain
      run: rustup update
    - name: Build rustwii
      run: cargo build --verbose --release
    - name: Package rustwii for Upload
      run: |
        mv target/release/rustwii ~/rustwii
        cd ~
        tar cvf rustwii.tar rustwii
    - name: Upload rustwii
      uses: actions/upload-artifact@v4
      with:
        path: ~/rustwii.tar
        name: rustwii-Linux-bin

  build-macos-arm64:
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update Toolchain
      run: rustup update
    - name: Add ARM64 Target
      run: rustup target add aarch64-apple-darwin
    - name: Build rustwii
      run: cargo build --verbose --release --target aarch64-apple-darwin
    - name: Package rustwii for Upload
      run: |
        mv target/aarch64-apple-darwin/release/rustwii ~/rustwii
        cd ~
        tar cvf rustwii.tar rustwii
    - name: Upload rustwii
      uses: actions/upload-artifact@v4
      with:
        path: ~/rustwii.tar
        name: rustwii-macOS-arm64-bin

  build-macos-x86_64:
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update Toolchain
      run: rustup update
    - name: Add x86_64 Target
      run: rustup target add x86_64-apple-darwin
    - name: Build rustwii
      run: cargo build --verbose --release --target x86_64-apple-darwin
    - name: Package rustwii for Upload
      run: |
        mv target/x86_64-apple-darwin/release/rustwii ~/rustwii
        cd ~
        tar cvf rustwii.tar rustwii
    - name: Upload rustwii
      uses: actions/upload-artifact@v4
      with:
        path: ~/rustwii.tar
        name: rustwii-macOS-x86_64-bin

  build-windows-x86_64:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update Toolchain
      run: rustup update
    - name: Build rustwii
      run: cargo build --verbose --release
    - name: Upload rustwii
      uses: actions/upload-artifact@v4
      with:
        path: D:\a\rustwii\rustwii\target\release\rustwii.exe
        name: rustwii-Windows-bin

      
